KTB-03-04 Изучить теорию парсинга и распарсить файл
Hudzone/KotlinTelegramBot pull request #2
Opened 2024-08-27 17:58 UTC by Hudzone

2024-08-28 05:43 UTC, kaznikit requested changes

2024-08-28 05:43 UTC, kaznikit commented on src/main/kotlin/Main.kt
> +    private var correctAnswerCounter: Comparable<*> = 0,
можно это свойство сделать просто Int, а также не нужно делать его приватным, так как нам придется часто обращаться к нему в дальнейшем

2024-08-28 07:52 UTC, Hudzone commented on src/main/kotlin/Main.kt
> +    private var correctAnswerCounter: Comparable<*> = 0,
@kaznikit поменял тип потому что у меня при null проверке выше типы конфликтили. 
Поэтому добавил отдельную проверку для третьего элемента списка, сейчас должно быть все корректно.

2024-08-29 05:18 UTC, kaznikit approved these changes

2024-08-29 07:39 UTC, merged