KTB-05 Разработать меню тренажера
Hudzone/KotlinTelegramBot pull request #3
Opened 2024-08-29 16:49 UTC by Hudzone

2024-08-30 05:46 UTC, kaznikit requested changes

2024-08-30 05:46 UTC, kaznikit commented on src/main/kotlin/Main.kt
> +fun mainMenu() {
названия функций должны быть в инфинитиве, можно назвать `createMainMenu` или `displayMainMenu`

2024-08-30 05:46 UTC, kaznikit commented on src/main/kotlin/Main.kt
> +
пустые строчки которые не разделяют идущий подряд код лучше убирать

2024-08-30 05:46 UTC, kaznikit commented on src/main/kotlin/Main.kt
> +
здесь тоже можно убрать

2024-08-30 05:46 UTC, kaznikit commented on src/main/kotlin/Main.kt
> +
и здесь

2024-08-30 08:16 UTC, Hudzone commented on src/main/kotlin/Main.kt
> +
Понял, принял)

2024-08-31 07:27 UTC, kaznikit approved these changes

2024-08-31 12:25 UTC, merged